import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from typing import Dict, Any, List
from acp_client import ACPClient

class AgentCommerce:
    def __init__(self, aap_api_url: str, acp_api_url: str):
        self.aap_client = ACPClient(aap_api_url)
        self.acp_client = ACPClient(acp_api_url)

    def register_service_provider(self, service_name: str, pricing_model: str, price_per_token: float = 0.0, price_per_task: float = 0.0) -> Dict[str, Any]:
        # Register the agent as a service provider with the specified pricing model
        return {
            "service_name": service_name,
            "pricing_model": pricing_model,
            "price_per_token": price_per_token,
            "price_per_task": price_per_task
        }

    def set_pricing_strategy(self, strategy: str, parameters: Dict[str, Any]) -> Dict[str, Any]:
        # Set the pricing strategy for the agent
        return {
            "strategy": strategy,
            "parameters": parameters
        }

    def track_revenue(self, service_name: str, revenue_amount: float) -> Dict[str, Any]:
        # Track revenue generated by the service
        return {
            "service_name": service_name,
            "revenue_amount": revenue_amount
        }

    def generate_profit_report(self, start_date: str, end_date: str) -> Dict[str, Any]:
        # Generate a profit report for the specified date range
        return {
            "start_date": start_date,
            "end_date": end_date,
            "profit_report": "Generated profit report"
        }

    def handle_inquiry(self, inquiry_data: Dict[str, Any]) -> Dict[str, Any]:
        # Handle an inquiry from a buyer
        return {
            "inquiry_data": inquiry_data,
            "response": "Inquiry handled successfully"
        }

    def place_order(self, order_data: Dict[str, Any]) -> Dict[str, Any]:
        # Place an order using the ACP client
        return self.acp_client.place_order(order_data)

    def process_payment(self, payment_data: Dict[str, Any]) -> Dict[str, Any]:
        # Process a payment using the ACP client
        return self.acp_client.process_payment(payment_data)