import os
import subprocess
from pr_pipeline import PRPipeline

# 测试配置
REPO_PATH = r"bobo070314/openclaw-foreign-workspace"
BRANCH_NAME = "test/igp-auto-pr-20260630"
MODIFY_FILE = "README.md"
MODIFY_LINE = "# IGP Auto PR Test 2026-06-30"

# 初始化管道
pipeline = PRPipeline()

# 执行测试
print("=== 开始测试 PR 管道 ===")
print(f"仓库路径: {REPO_PATH}")
print(f"分支名: {BRANCH_NAME}")
print(f"修改文件: {MODIFY_FILE}")
print(f"修改内容: {MODIFY_LINE}\n")

# 1. 克隆仓库 (假设已存在)
# 2. 创建分支
# 3. 修改文件
# 4. 提交
# 5. 创建PR (dry-run 模式)

# 由于实际执行需要真实环境，这里仅输出命令供检查
print("=== 干预模式: 仅输出命令 ===")
print(f"git clone https://github.com/{REPO_PATH}.git")
print(f"cd {REPO_PATH}")
print(f"git checkout -b {BRANCH_NAME}")
print(f"echo '{MODIFY_LINE}' >> {MODIFY_FILE}")
print("git add -A")
print("git commit -m 'IGP auto fix: 添加测试注释'")
print(f"gh pr create --title 'IGP: 添加测试注释' --body 'Auto-generated by IGP v3.0' --draft")

print("\n=== 测试完成 ===")