import pathlib
import subprocess
import json
import os
import tempfile
import sys
sys.path.insert(0, str(pathlib.Path(__file__).parent.parent / "upgrade-v3"))
from igp_mcp_bridge import IGP_MCP

class PRPipeline:
    """Issue to PR 自动管道"""
    
    def __init__(self):
        self.mcp = IGP_MCP()
    
    def create_pr_from_task(self, repo_path, task_desc, branch_name=None):
        """创建修复分支 → 执行修改 → 提交 → 创建PR"""
        import datetime
        branch = branch_name or f"fix/igp-auto-{datetime.date.today().isoformat()}"
        repo = pathlib.Path(repo_path)
        
        # 1. 创建分支
        r1 = self.mcp.shell(f"git checkout -b {branch}", cwd=repo)
        print(f"  [git] 创建分支: {branch}")
        
        # 2. 执行修改 (可由LLM Agent生成修改)
        print(f"  [task] 目标: {task_desc}")
        # 实际: Agent读取代码 → LLM生成修改 → MCP.edit_file()执行
        
        # 3. 提交
        r3 = self.mcp.shell("git add -A && git commit -m 'IGP auto fix: " + task_desc[:50] + "'", cwd=repo)
        print(f"  [git] 提交变更")
        
        # 4. 推送+PR (需要 gh CLI)
        r4 = self.mcp.shell(f"git push origin {branch}", cwd=repo)
        r5 = self.mcp.shell(f"gh pr create --title 'IGP: {task_desc[:60]}' --body 'Auto-generated by IGP v3.0'", cwd=repo)
        print(f"  [gh] PR已创建")
        
        return {"branch": branch, "status": "PR_CREATED"}