#!/usr/bin/env python3.
"""api-doc-generator v0.2.0 — Auto-generate API docs from source code.

Supports OpenAPI 3.0 and Markdown output from Python/Node.js/Go source.

Usage:
  python run.py --path ./src --format openapi
  python run.py --path ./routes --format markdown --output api.md
  python run.py --dry-run --json --version
"""

import argparse
import json
import sys
from pathlib import Path

__version__ = "0.2.0"

ENDPOINT_PATTERNS = {
    ".py": [
        (r"@app\.(get|post|put|delete|patch)\([\"']([^\"']+)[\"']", "Flask/FastAPI"),
        (r"@router\.(get|post|put|delete|patch)\([\"']([^\"']+)[\"']", "FastAPI"),
        (r"@blueprint\.(route)\([\"']([^\"']+)[\"'].*methods=\[([^\]]+)\]", "Flask"),
    ],
    ".js": [
        (r"app\.(get|post|put|delete|patch)\([\"']([^\"']+)[\"']", "Express"),
        (r"router\.(get|post|put|delete|patch)\([\"']([^\"']+)[\"']", "Express Router"),
    ],
    ".ts": [
        (r"@(Get|Post|Put|Delete|Patch)\([\"']([^\"']+)[\"']", "NestJS"),
        (r"@(Get|Post|Put|Delete|Patch)\(\)", "NestJS (no path)"),
    ],
    ".go": [
        (r"\.(GET|POST|PUT|DELETE|PATCH)\([\"']([^\"']+)[\"']", "Gin"),
        (r"HandleFunc\([\"']([^\"']+)[\"']", "net/http"),
    ],
}


def scan_endpoints(path: str) -> list:
    """Scan source files for API endpoint definitions."""
    import re

    endpoints = []
    base = Path(path)

    if not base.exists():
        return endpoints

    for fp in base.rglob("*"):
        if fp.suffix not in ENDPOINT_PATTERNS:
            continue
        try:
            content = fp.read_text(encoding="utf-8", errors="replace")
        except Exception:
            continue

        for pattern, framework in ENDPOINT_PATTERNS.get(fp.suffix, []):
            for match in re.finditer(pattern, content, re.IGNORECASE):
                method = match.group(1).upper()
                route = match.group(2) if len(match.groups()) >= 2 else "/"
                endpoints.append(
                    {
                        "method": method,
                        "path": route,
                        "file": str(fp.relative_to(base)),
                        "framework": framework,
                        "line": content[: match.start()].count("\n") + 1,
                    }
                )

    return endpoints


def generate_openapi(endpoints: list, title: str = "API") -> dict:
    """Generate OpenAPI 3.0 spec."""
    spec = {
        "openapi": "3.0.3",
        "info": {"title": title, "version": "1.0.0", "description": "Auto-generated by api-doc-generator"},
        "paths": {},
    }

    for ep in endpoints:
        if ep["path"] not in spec["paths"]:
            spec["paths"][ep["path"]] = {}
        spec["paths"][ep["path"]][ep["method"].lower()] = {
            "summary": f"{ep['method']} {ep['path']}",
            "description": f"Defined in {ep['file']}:{ep['line']} ({ep['framework']})",
            "responses": {"200": {"description": "OK"}},
        }

    return spec


def generate_markdown(endpoints: list, title: str = "API") -> str:
    """Generate Markdown documentation."""
    lines = [
        f"# {title} API Documentation",
        "",
        f"*Auto-generated by api-doc-generator v{__version__}*",
        "",
        f"**Total endpoints:** {len(endpoints)}",
        "",
        "| Method | Path | File | Framework |",
        "|--------|------|------|-----------|",
    ]
    for ep in endpoints:
        lines.append(f"| {ep['method']} | `{ep['path']}` | {ep['file']}:{ep['line']} | {ep['framework']} |")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="API Doc Generator v0.2.0")
    parser.add_argument("--path", default=".", help="Source code directory")
    parser.add_argument("--format", choices=["openapi", "markdown"], default="openapi", help="Output format")
    parser.add_argument("--output", help="Output file path")
    parser.add_argument("--title", default="API", help="API title")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--version", action="store_true")

    args = parser.parse_args()

    if args.version:
        print(__version__)
        return

    if args.dry_run:
        result = {
            "dry_run": True,
            "path": args.path,
            "format": args.format,
            "actions": ["scan", "parse", "generate"],
        }
        print(json.dumps(result, indent=2) if args.json else "📄 API Doc Generator dry-run — ready")
        return

    endpoints = scan_endpoints(args.path)

    if args.format == "markdown":
        output = generate_markdown(endpoints, args.title)
    else:
        spec = generate_openapi(endpoints, args.title)
        output = json.dumps(spec, indent=2)

    if args.json:
        print(json.dumps({"endpoints_found": len(endpoints), "format": args.format}, indent=2))
    elif args.output:
        Path(args.output).write_text(output, encoding="utf-8")
        print(f"✅ Written {len(endpoints)} endpoints → {args.output}")
    else:
        print(output)


if __name__ == "__main__":
    main()
