"""
auto_fixer_demo.py — 10-second demo script for A-line customer followup.
Shows: input a fail_reason → auto_fixer categorizes it → outputs repair template name.

Colors: green=success, blue=info, red=error, cyan=headers.

Usage:
    python scripts/auto_fixer_demo.py         # run demo
    python scripts/auto_fixer_demo.py --cleanup # delete generated template files
"""

import sys
from pathlib import Path

# ANSI color codes (defined before --cleanup early exit)
GREEN = "\033[92m"
BLUE = "\033[94m"
CYAN = "\033[96m"
YELLOW = "\033[93m"
RED = "\033[91m"
BOLD = "\033[1m"
RESET = "\033[0m"

sys.path.insert(0, str(Path("scripts").resolve()))
from auto_fixer import analyze_failures, select_strategy, apply_repair

# ── Cleanup helper ──
CLEANUP_TARGETS = [
    Path("configs/agent_chain.yaml"),
    Path("README.deliver.md"),
]


def cleanup_generated():
    """Delete template files generated by apply_repair during demo."""
    removed = 0
    for p in CLEANUP_TARGETS:
        if p.exists():
            p.unlink()
            removed += 1
            print(f"  {GREEN}Deleted:{RESET} {p}")
    if not removed:
        print(f"  {GREEN}Nothing to clean.{RESET}")
    return removed


if "--cleanup" in sys.argv:
    cleanup_generated()
    sys.exit(0)


# Simulate eval failure scenarios
test_failures = [
    "missing file: configs/agent_chain.yaml",
    "invalid config: bad configuration value",
    "rbac: permission denied for user coder",
]

print(f"{CYAN}{'=' * 52}{RESET}")
print(f"{BOLD}{CYAN}  auto_fixer demo — input → categorize → repair{RESET}")
print(f"{CYAN}{'=' * 52}{RESET}")

for fail_reason in test_failures:
    eval_data = {
        "pass_rate": 0.0,
        "checks": [{
            "name": "demo_check",
            "status": "fail",
            "fail_reason": fail_reason
        }]
    }
    analysis = analyze_failures(eval_data)
    plan = select_strategy(analysis)
    result_path = apply_repair(plan["strategy"])

    category = analysis["failures"][0]["category"]
    strategy = plan["strategy"]
    confidence = plan["confidence"]

    # Color by category
    if category == "FileMissing":
        cat_color = YELLOW
    elif category == "ConfigError":
        cat_color = BLUE
    elif category == "RBACViolation":
        cat_color = RED
    else:
        cat_color = RESET

    print(f"\n  {BOLD}{CYAN}── Input{RESET}")
    print(f"     {BLUE}fail_reason:{RESET} {fail_reason}")
    print(f"  {BOLD}{CYAN}── Result{RESET}")
    print(f"     {GREEN}category:{RESET}   {cat_color}{category}{RESET}")
    print(f"     {GREEN}strategy:{RESET}   {cat_color}{strategy}{RESET}")
    print(f"     {GREEN}confidence:{RESET} {cat_color}{confidence}{RESET}")
    print(f"     {GREEN}applied to:{RESET} {result_path}")

print(f"\n{CYAN}{'=' * 52}{RESET}")
print(f"  {GREEN}✅ 10-second demo complete.{RESET}")
print(f"{CYAN}{'=' * 52}{RESET}")

# Auto-cleanup after demo
removed = cleanup_generated()
if removed:
    print(f"  {GREEN}✅ Auto-cleaned {removed} generated file(s).{RESET}")
print(f"  {GREEN}Run --cleanup anytime to remove templates.{RESET}")
